# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1etc5ITFoRzPSi0LJD1gbJCLFDUyAjOrr
"""

import torch
import torch.nn as nn
import torch.optim as optim
import torchvision
import torchvision.transforms as transforms
import matplotlib.pyplot as plt
import numpy as np

class PrunableLinear(nn.Module):
    def __init__(self, in_features, out_features):
        super(PrunableLinear, self).__init__()
        self.in_features = in_features
        self.out_features = out_features


        self.weight = nn.Parameter(torch.Tensor(out_features, in_features))
        self.bias = nn.Parameter(torch.Tensor(out_features))


        self.gate_scores = nn.Parameter(torch.Tensor(out_features, in_features))


        nn.init.kaiming_uniform_(self.weight, a=np.sqrt(5))
        nn.init.constant_(self.bias, 0)

        nn.init.constant_(self.gate_scores, 1.0)

    def forward(self, x):

        gates = torch.sigmoid(self.gate_scores)

        pruned_weights = self.weight * gates
        return nn.functional.linear(x, pruned_weights, self.bias)

    def get_sparsity_loss(self):

        return torch.sum(torch.sigmoid(self.gate_scores))

class SelfPruningNet(nn.Module):
    def __init__(self):
        super(SelfPruningNet, self).__init__()
        self.flatten = nn.Flatten()
        self.fc1 = PrunableLinear(32 * 32 * 3, 512)
        self.fc2 = PrunableLinear(512, 256)
        self.fc3 = PrunableLinear(256, 10)
        self.relu = nn.ReLU()

    def forward(self, x):
        x = self.flatten(x)
        x = self.relu(self.fc1(x))
        x = self.relu(self.fc2(x))
        x = self.fc3(x)
        return x

    def total_sparsity_loss(self):
        return self.fc1.get_sparsity_loss() + \
               self.fc2.get_sparsity_loss() + \
               self.fc3.get_sparsity_loss()


def train_and_evaluate(lam, epochs=5):
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    transform = transforms.Compose([transforms.ToTensor(), transforms.Normalize((0.5,), (0.5,))])
    trainset = torchvision.datasets.CIFAR10(root='./data', train=True, download=True, transform=transform)
    trainloader = torch.utils.data.DataLoader(trainset, batch_size=64, shuffle=True)

    testset = torchvision.datasets.CIFAR10(root='./data', train=False, download=True, transform=transform)
    testloader = torch.utils.data.DataLoader(testset, batch_size=64, shuffle=False)

    model = SelfPruningNet().to(device)
    optimizer = optim.Adam(model.parameters(), lr=1e-3)
    criterion = nn.CrossEntropyLoss()

    for epoch in range(epochs):
        model.train()
        for inputs, labels in trainloader:
            inputs, labels = inputs.to(device), labels.to(device)
            optimizer.zero_grad()

            outputs = model(inputs)
            ce_loss = criterion(outputs, labels)
            sparsity_loss = model.total_sparsity_loss()

            total_loss = ce_loss + lam * sparsity_loss
            total_loss.backward()
            optimizer.step()
    model.eval()
    correct = 0
    total = 0
    all_gates = []

    with torch.no_grad():
        for inputs, labels in testloader:
            inputs, labels = inputs.to(device), labels.to(device)
            outputs = model(inputs)
            _, predicted = torch.max(outputs.data, 1)
            total += labels.size(0)
            correct += (predicted == labels).sum().item()


        total_weights = 0
        pruned_weights = 0
        for name, param in model.named_parameters():
            if 'gate_scores' in name:
                gates = torch.sigmoid(param)
                all_gates.extend(gates.view(-1).cpu().numpy())
                total_weights += gates.numel()
                pruned_weights += (gates < 1e-2).sum().item()

    accuracy = 100 * correct / total
    sparsity_pct = 100 * pruned_weights / total_weights
    return accuracy, sparsity_pct, all_gates


lambdas = [1e-5, 1e-4, 1e-3]
results = []
gate_distributions = {}

for l in lambdas:
    print(f"Testing Lambda: {l}")
    acc, sp, gates = train_and_evaluate(l)
    results.append((l, acc, sp))
    gate_distributions[l] = gates

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
plt.figure(figsize=(10, 6))
plt.hist(gate_distributions[1e-4], bins=50, color='skyblue', edgecolor='black')
plt.title("Distribution of Final Gate Values ($\\lambda = 10^{-4}$)")
plt.xlabel("Gate Value ($\\sigma(gate\\_scores)$)")
plt.ylabel("Frequency")
plt.yscale('log')
plt.grid(axis='y', alpha=0.3)
plt.show()